// <auto-generated />
using System;
using MailManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailManager.Api.Data.Migrations
{
    [DbContext(typeof(MailManagerDbContext))]
    [Migration("20260811013212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailManager.Api.Domain.ClassificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("BodyKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationLabelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string[]>("SenderAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("SenderDomains")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("SubjectKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLabelId");

                    b.HasIndex("MailboxConnectionId", "Priority");

                    b.ToTable("ClassificationRules");
                });

            modelBuilder.Entity("MailManager.Api.Domain.LabelDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalLabelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxConnectionId", "Name")
                        .IsUnique();

                    b.ToTable("LabelDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "#2563eb",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MailboxConnectionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Projet Démo"
                        });
                });

            modelBuilder.Entity("MailManager.Api.Domain.MailboxConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MailboxConnections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Boîte Gmail de démonstration",
                            IsActive = true,
                            Provider = "Gmail"
                        });
                });

            modelBuilder.Entity("MailManager.Api.Domain.ProcessingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationLabelId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationLabelName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsClassified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string[]>("MatchedCriteria")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("MatchedRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchedRuleName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NoMatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MailboxConnectionId", "ExternalMessageId")
                        .IsUnique();

                    b.ToTable("ProcessingLogs");
                });

            modelBuilder.Entity("MailManager.Api.Domain.ClassificationRule", b =>
                {
                    b.HasOne("MailManager.Api.Domain.LabelDefinition", "DestinationLabel")
                        .WithMany("Rules")
                        .HasForeignKey("DestinationLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MailManager.Api.Domain.MailboxConnection", "MailboxConnection")
                        .WithMany("Rules")
                        .HasForeignKey("MailboxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationLabel");

                    b.Navigation("MailboxConnection");
                });

            modelBuilder.Entity("MailManager.Api.Domain.LabelDefinition", b =>
                {
                    b.HasOne("MailManager.Api.Domain.MailboxConnection", "MailboxConnection")
                        .WithMany("Labels")
                        .HasForeignKey("MailboxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailboxConnection");
                });

            modelBuilder.Entity("MailManager.Api.Domain.ProcessingLog", b =>
                {
                    b.HasOne("MailManager.Api.Domain.MailboxConnection", "MailboxConnection")
                        .WithMany("ProcessingLogs")
                        .HasForeignKey("MailboxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailboxConnection");
                });

            modelBuilder.Entity("MailManager.Api.Domain.LabelDefinition", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("MailManager.Api.Domain.MailboxConnection", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("ProcessingLogs");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
