// <auto-generated />
using System;
using MailManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailManager.Api.Data.Migrations
{
    [DbContext(typeof(MailManagerDbContext))]
    [Migration("20260825175224_AddLegalCompliance")]
    partial class AddLegalCompliance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailManager.Api.Domain.ClassificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("BodyKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationLabelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string[]>("SenderAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("SenderDomains")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string[]>("SubjectKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLabelId");

                    b.HasIndex("MailboxConnectionId", "Priority");

                    b.ToTable("ClassificationRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BodyKeywords = new string[0],
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DestinationLabelId = new Guid("55555555-5555-5555-5555-555555555555"),
                            IsActive = true,
                            MailboxConnectionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            MatchMode = "Any",
                            Name = "Projet Alpha",
                            Priority = 10,
                            SenderAddresses = new string[0],
                            SenderDomains = new[] { "client.fr" },
                            SubjectKeywords = new[] { "projet alpha" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MailManager.Api.Domain.GmailOAuthConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EncryptedClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GmailOAuthConfigurations");
                });

            modelBuilder.Entity("MailManager.Api.Domain.LabelDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalLabelId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxConnectionId", "Name")
                        .IsUnique();

                    b.ToTable("LabelDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "#2563eb",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MailboxConnectionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Projet Démo"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Color = "#c64a2f",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            MailboxConnectionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Projet Démo"
                        });
                });

            modelBuilder.Entity("MailManager.Api.Domain.LegalAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrivacyVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSubject")
                        .IsUnique();

                    b.ToTable("LegalAcceptances");
                });

            modelBuilder.Entity("MailManager.Api.Domain.MailboxConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("GrantedScopes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OwnerSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiresReconnect")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSubject");

                    b.ToTable("MailboxConnections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Boîte Gmail de démonstration",
                            IsActive = true,
                            OwnerSubject = "10000000-0000-0000-0000-000000000001",
                            Provider = "Gmail",
                            RequiresReconnect = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Boîte de démonstration",
                            IsActive = true,
                            OwnerSubject = "10000000-0000-0000-0000-000000000002",
                            Provider = "Gmail",
                            RequiresReconnect = false
                        });
                });

            modelBuilder.Entity("MailManager.Api.Domain.ProcessingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationLabelId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationLabelName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsClassified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MailboxConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string[]>("MatchedCriteria")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("MatchedRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchedRuleName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MatchedRulePriority")
                        .HasColumnType("integer");

                    b.Property<string>("NoMatchReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderActionError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ProviderLabelAppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectPreview")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("MailboxConnectionId", "ExternalMessageId")
                        .IsUnique();

                    b.ToTable("ProcessingLogs");
                });

            modelBuilder.Entity("MailManager.Api.Domain.ClassificationRule", b =>
                {
                    b.HasOne("MailManager.Api.Domain.LabelDefinition", "DestinationLabel")
                        .WithMany("Rules")
                        .HasForeignKey("DestinationLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MailManager.Api.Domain.MailboxConnection", "MailboxConnection")
                        .WithMany("Rules")
                        .HasForeignKey("MailboxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationLabel");

                    b.Navigation("MailboxConnection");
                });

            modelBuilder.Entity("MailManager.Api.Domain.LabelDefinition", b =>
                {
                    b.HasOne("MailManager.Api.Domain.MailboxConnection", "MailboxConnection")
                        .WithMany("Labels")
                        .HasForeignKey("MailboxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailboxConnection");
                });

            modelBuilder.Entity("MailManager.Api.Domain.ProcessingLog", b =>
                {
                    b.HasOne("MailManager.Api.Domain.MailboxConnection", "MailboxConnection")
                        .WithMany("ProcessingLogs")
                        .HasForeignKey("MailboxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailboxConnection");
                });

            modelBuilder.Entity("MailManager.Api.Domain.LabelDefinition", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("MailManager.Api.Domain.MailboxConnection", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("ProcessingLogs");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
